server:
  port: 0 # random port

# add the application name to register thia application on eureka-server
spring:
  application:
    name: 'client'

# eureka client configs
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka