server:
  port: 9001
  
spring:
  application:
    name: 'calculator'
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka