server:
  port: 5555
  
spring:  application:    name: gateway
  cloud:    gateway:      discovery:        locator:          enabled: true
      routes:
      - id: calculator
        uri: http://localhost:9001
        predicates:        - Path=/math/**
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/