server:
  port: 9002

spring:
  application:
    name: 'client'
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


resilience4j:
  circuitbreaker:
    instances:
      sum:
        slidingWindowSize: 3 # It is based on the last 3 requests to build the statistics for the open or closed state
        minimumNumberOfCalls: 2 # Defines the number of requests before transitioning to the open state
        waitDurationInOpenState: 10s # Defines the amount of time the service will remain in the open state before transitioning to half-open
