# eureka default port
server:
  port: 8761
  
# eureka server configs
eureka:
  client:
    # the settings below ensure that this application does not register itself, as its use is exclusively for service discovery
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'