server:
  port: 9001
  
spring:
  application:
    name: 'calculator'
    
eureka:
  client:
    fetch-registry: true # controls if Eureka should retrieve all services registered on eureka server
    register-with-eureka: true # controls if service should or should not register on eureka server
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS